---
# tasks file for jenkinslts - EL Family

# - name: EL Family | Installing {{ jenkinslts_javadependency_el }} as it is required for {{ jenkinslts_app_name }}.
#   yum:
#     name: "{{ jenkinslts_javadependency_el }}"
#     state: "{{ jenkinslts_javadependency_el_desired_state }}"
#     update_cache: yes

- name: EL Family | Add group "{{ jenkinslts_user }}" as a pre-requisite for "{{ jenkinslts_app_name }}"
  group:
    name: "{{ jenkinslts_group }}"
    state: "{{ jenkinslts_user_desired_state }}"

- name: EL Family | Add user "{{ jenkinslts_user }}" as a pre-requisite for "{{ jenkinslts_app_name }}"
  user:
    name: "{{ jenkinslts_user }}"
    comment: Jenkins Automation Server
    group: "{{ jenkinslts_group }}"
    home: "{{ jenkinslts_user_home }}"
    shell: "{{ jenkinslts_user_shell }}"
    state: "{{ jenkinslts_user_desired_state }}"

- name: EL Family | Adding repository {{ jenkinslts_repo_el }}
  yum_repository:
    name: "{{ jenkinslts_repo_el_name }}"
    description: "{{ jenkinslts_repo_el_description }}"
    baseurl: "{{ jenkinslts_repo_el }}"
    gpgcheck: "{{ jenkinslts_repo_el_gpgcheck }}"
    gpgkey: "{{ jenkinslts_el_gpg_key }}"
    file: "{{ jenkinslts_repo_el_filename }}"
    state: "{{ jenkinslts_repo_desired_state }}"

- name: EL Family | Installing {{ jenkinslts_app_name }}
  yum:
    name: "{{ jenkinslts_app_name }}"
    state: "{{ jenkinslts_desired_state }}"
    update_cache: yes
  notify:
    - "set_{{ jenkinslts_app_name }}_user_on_el_systems"
    - "set_{{ jenkinslts_app_name }}_home_on_el_systems"
    - "set_{{ jenkinslts_app_name }}_http_port_on_el_systems"
    - "set_{{ jenkinslts_app_name }}_heapsize_max_on_el_systems"
    - "set_{{ jenkinslts_service_name }}_service_state"
    - "set_{{ jenkinslts_service_name }}_service_boot_state"
    - "check_{{ jenkinslts_app_name }}_url"
    - "register_{{ jenkinslts_app_name }}_admin_password"
    - "print_{{ jenkinslts_app_name }}_admin_password"
