---
# tasks file for jenkinslts - EL Family

- name: EL Family | Add group "{{ jenkinslts_user }}" as a pre-requisite for "{{ jenkinslts_app_name }}"
  group:
    name: "{{ jenkinslts_group }}"
    state: "{{ jenkinslts_user_desired_state }}"

- name: EL Family | Add user "{{ jenkinslts_user }}" as a pre-requisite for "{{ jenkinslts_app_name }}"
  user:
    name: "{{ jenkinslts_user }}"
    comment: Jenkins Automation Server
    group: "{{ jenkinslts_group }}"
    home: "{{ jenkinslts_user_home }}"
    shell: "{{ jenkinslts_user_shell }}"
    state: "{{ jenkinslts_user_desired_state }}"

- name: EL Family | Adding repository {{ jenkinslts_repo_el }}
  yum_repository:
    name: "{{ jenkinslts_repo_el_name }}"
    description: "{{ jenkinslts_repo_el_description }}"
    baseurl: "{{ jenkinslts_repo_el }}"
    gpgcheck: "{{ jenkinslts_repo_el_gpgcheck }}"
    gpgkey: "{{ jenkinslts_el_gpg_key }}"
    file: "{{ jenkinslts_repo_el_filename }}"
    state: "{{ jenkinslts_repo_desired_state }}"

- name: EL Family | Installing {{ jenkinslts_app_name }}
  yum:
    name: "{{ jenkinslts_app_name }}"
    state: "{{ jenkinslts_desired_state }}"
    update_cache: yes
  notify:
    - "EL Family | Set JENKINS_USER for jenkins"
    - "EL Family | Set JENKINS_HOME for jenkins"
    - "EL Family | Set JENKINS_PORT for jenkins"
    - "EL Family | Set JENKINS_ARGS max heapsize for jenkins"
    - "Set {{ jenkinslts_service_name }} service state"
    - "Set {{ jenkinslts_service_name }} service boot state"
    - "Check {{ jenkinslts_app_name }} url for status code {{ jenkinslts_app_check_status_code }}"
    - "Register {{ jenkinslts_app_name }} Admin password"
    - "Print {{ jenkinslts_app_name }} Admin Password"
