---
# handlers file for jenkins

## Debian/Ubuntu Family Related
- name: "Debian/Ubuntu Family | Set JENKINS_USER for jenkins"
  lineinfile:
    path: "{{ jenkinslts_default_debain_config_file }}"
    regexp: '^JENKINS\_USER\=[a-zA-Z]*'
    line: "JENKINS_USER={{ jenkinslts_user }}"
    state: present
    backup: yes

- name: "Debian/Ubuntu Family | Set JENKINS_GROUP for jenkins"
  lineinfile:
    path: "{{ jenkinslts_default_debain_config_file }}"
    regexp: '^JENKINS\_GROUP\=[a-zA-Z]*'
    line: "JENKINS_GROUP={{ jenkinslts_group }}"
    state: present
    backup: yes

- name: "Debian/Ubuntu Family | Set JENKINS_HOME for jenkins"
  lineinfile:
    path: "{{ jenkinslts_default_debain_config_file }}"
    regexp: '^JENKINS\_HOME\=[a-zA-Z/]'
    line: "JENKINS_HOME={{ jenkinslts_user_home }}"
    state: present
    backup: yes

- name: "Debian/Ubuntu Family | Set HTTP_PORT for jenkins"
  lineinfile:
    path: "{{ jenkinslts_default_debain_config_file }}"
    regexp: '^HTTP\_PORT\=[0-9]*'
    line: "HTTP_PORT={{ jenkinslts_app_port }}"
    state: present
    backup: yes

- name: "Debian/Ubuntu Family | Set JAVA_ARGS max heapsize for jenkins"
  lineinfile:
    path: "{{ jenkinslts_default_debain_config_file }}"
    regexp: '^#JAVA\_ARGS\=\"\-Xmx[0-9]*m\"'
    line: 'JAVA_ARGS="-Xmx{{ jenkinslts_app_heapsize_max }}"'
    state: present
    backup: yes
## Debian/Ubuntu Family Related


## EL Family Related
- name: "EL Family | Set JENKINS_USER for jenkins"
  lineinfile:
    path: "{{ jenkinslts_default_el_config_file }}"
    regexp: '^JENKINS\_USER\=\"[a-zA-Z]*\"'
    line: 'JENKINS_USER="{{ jenkinslts_user }}"'
    state: present
    backup: yes

- name: "EL Family | Set JENKINS_HOME for jenkins"
  lineinfile:
    path: "{{ jenkinslts_default_el_config_file }}"
    regexp: '^JENKINS\_HOME\=\"*[a-zA-Z0-9]*\"'
    line: 'JENKINS_HOME="{{ jenkinslts_user_home }}"'
    state: present
    backup: yes

- name: "EL Family | Set JENKINS_PORT for jenkins"
  lineinfile:
    path: "{{ jenkinslts_default_el_config_file }}"
    regexp: '^JENKINS\_PORT\=\"[0-9]*\"'
    line: 'JENKINS_PORT="{{ jenkinslts_app_port }}"'
    state: present
    backup: yes

- name: "EL Family | Set JENKINS_ARGS max heapsize for jenkins"
  lineinfile:
    path: "{{ jenkinslts_default_el_config_file }}"
    regexp: '^JENKINS\_ARGS\=\"\"'
    line: 'JENKINS_ARGS="-Xmx{{ jenkinslts_app_heapsize_max }}"'
    state: present
    backup: yes
## EL Family Related


## COMMON BETWEEN OPERATING SYSTEMS
- name: "Set {{ jenkinslts_service_name }} service state"
  service:
    name: "{{ jenkinslts_service_name }}"
    state: "{{ jenkinslts_service_desired_state }}"

- name: "Set {{ jenkinslts_service_name }} service boot state"
  service:
    name: "{{ jenkinslts_service_name }}"
    enabled: "{{ jenkinslts_service_desired_boot_enabled }}"

- name: "Check {{ jenkinslts_app_name }} url for status code {{ jenkinslts_app_check_status_code }}"
  uri:
    url: "http://localhost:{{ jenkinslts_app_port }}/login"
    status_code: "{{ jenkinslts_app_check_status_code }}"
  retries: "{{ jenkinslts_app_check_status_code_retries }}"
  delay: "{{ jenkinslts_app_check_status_code_delay }}"
  register: result
  until: ('status' in result) and (result.status == 200)

- name: "Register {{ jenkinslts_app_name }} Admin password"
  slurp:
    src: "{{ jenkinslts_app_admin_password_file }}"
  register: jenkins_admin_password

- name: "Print {{ jenkinslts_app_name }} Admin Password"
  debug:
    msg: "Jenkins initial admin password is: {{ jenkins_admin_password['content'] }}"
## COMMON BETWEEN OPERATING SYSTEMS
